# Site settings
title: Many Hats Software 
email: doug@manyhatssoftware.com
description: "Custom software created by craftsmen. Software done right."
baseurl: "http://www.manyhatssoftware.com"
url: "http://www.manyhatssoftware.com"
twitter_username: DougMulley
github_username:  manyhatssoftware

# Build settings
markdown: kramdown
permalink: pretty
